openapi: 3.0.0
servers:
  - url: http://localhost:8080
    description: Api Back-end (DIRECT-SINCRO)
  - url: http://localhost:3000
    description: Simulador do SIGET
info:
  description: This
  version: "1.0.0"
  title: Direct-Sincro Api
tags:
  - name: Administradores
    description: Rotas de administrador
  - name: Subscritores
    description: Operações disponiveis para cidadãos que ja se subscreveram à api
  - name: Cidadao
    description: Operações disponiveis para cidadãos sem sessao iniciada
  - name: Simulador do SIGET 
    description: Adicionar contraodenação
paths:
  /api/subscritores/{nif}/veiculos/{matricula}/contraordenacoes:
    post:
      tags:
        - Subscritores
      summary: Associar contraordenação ao proprietário
      operationId: "adicionarEventoAEmprestar"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: matricula
        in: path
        description: matricula do veiculo
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contraordenacao"
      responses:
        '201':
          description: O pedido foi enviado com sucesso 
        '400':
          description: Algum parametro estava incorreto
        '409': 
          description: O pedido ja se encontra criado.
    get:
      tags:
        - Subscritores
      summary: Obter contraordenações do veiculo
      operationId: "obterEventoMatricula"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: matricula
        in: path
        description: matricula do veiculo
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Contraordenações do veiculo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contraordenacao"
        '400':
          description: Algum parametro estava incorreto

  /api/subscritores/{nif}/alugados/{matricula}/contraordenacoes:
    post:
      tags:
        - Subscritores
      summary: Associar contraordenacao ao responsavel pelo Delegacao
      operationId: "adicionarEventoEmprestado"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: matricula
        in: path
        description: matricula do veiculo
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contraordenacao"
      responses:
        '201':
          description: O pedido foi enviado com sucesso 
        '400':
          description: Algum parametro estava incorreto
        '409': 
          description: O pedido ja se encontra criado.

  /api/subscritores/{nif}/delegacoes?matricula=string&datainicio=long:
    get:
      tags:
        - Subscritores
      summary: Requerer os Delegacoes deste veiculo com data de inicio pretendida
      operationId: "pedirDelegacoesComData"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - in: query
        name: matricula
        description: matricula do veiculo
        required: true
        schema:
          type: string
      - in: query
        name: datainicio
        required: true
        schema:
          type: integer
        description: data em que Delegacao iniciou
      responses:
        '200':
          description: Delegacoes do veiculo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delegacao'
        '400':
          description: Algum parametro estava incorreto
        '404': 
          description: O pedido não foi encontrado

  /api/subscritores/{nif}/veiculos/{matricula}/delegacoes:
    get:
      tags:
        - Subscritores
      summary: Requerer os Delegacoes deste veiculo
      operationId: "pedirDelegacoes"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: matricula
        in: path
        description: matricula do veiculo
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Delegacoes do veiculo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delegacoes'
        '400':
          description: Algum parametro estava incorreto
        '404': 
          description: O pedido não foi encontrado
    post:
      tags:
        - Subscritores
      summary: Adicionar delegacao ao veiculo
      operationId: "fazerDelegacao"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: matricula
        in: path
        description: matricula do veiculo
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Delegacao"
      responses:
        '201':
          description: O pedido foi enviado com sucesso 
        '400':
          description: Algum parametro estava incorreto
        '409': 
          description: O pedido ja se encontra criado.

  /api/subscritores/{nif}/veiculos/{matricula}/contraordenacoes/{numeroauto}/pedido:
    post:
      tags:
        - Subscritores
      summary: Fazer pedido de defesa
      description: Fazer pedido de defesa associado ao evento especificado
      operationId: "fazerPedido"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: matricula
        in: path
        description: matricula do veiculo
        required: true
        schema:
          type: string
      - name: numeroauto
        in: path
        description: numero do Auto
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PedidoDeDefesa"
      responses:
        '201':
          description: O pedido foi enviado com sucesso 
        '400':
          description: Algum parametro estava incorreto
        '409': 
          description: O pedido ja se encontra criado.
    get:
      tags:
        - Subscritores
      summary: Requerer o pedido de defesa
      operationId: "pedirPedido"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: matricula
        in: path
        description: matricula do veiculo
        required: true
        schema:
          type: string
      - name: numeroauto
        in: path
        description: numero do Auto
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Pedido de defesa feito para numero de auto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PedidoDeDefesa'
        '400':
          description: Algum parametro estava incorreto
        '404': 
          description: O pedido não foi encontrado

  /api/subscritores/{nif}/veiculos/{matricula}/contraordenacoes/{numeroauto}:
    post:
      tags:
        - Subscritores
      summary: Fazer pagamento da Contraordenação
      description: Permite fazer a atualização do estado de pagamento da Contraordenação na base de dados de Direct-Sincro e no simulador SCOT
      operationId: "efetuarPagamento"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: matricula
        in: path
        description: matricula do veiculo
        required: true
        schema:
          type: string
      - name: numeroauto
        in: path
        description: numero do Auto
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: O pedido foi enviado com sucesso 
        '400':
          description: Algum parametro estava incorreto
        '409': 
          description: O pedido ja se encontra criado.

  /api/subscritores:
    post:
      tags:
        - Cidadao
      summary: Criar nova conta de Subscritor
      description: Cidadão devera inserir todos os parametros requeridos
      operationId: "criarSubscritor"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cidadao"
      responses:
        '201':
          description: O pedido foi enviado com sucesso 
        '400':
          description: Algum parametro estava incorreto
        '409': 
          description: O pedido ja se encontra criado.

  /api/subscritores/{nif}:
    get:
      tags:
        - Subscritores
      summary: Pedir informaçao de Subscritor
      operationId: "pedirSubscritor"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Toda a informaçao do Subscritor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscritor'
        '400':
          description: Algum parametro estava incorreto
        '404': 
          description: Recurso não encontrado

  /api/subscritores/{nif}/veiculos:
    post:
      tags:
        - Subscritores
      summary: Adicionar veiculo ao subscritor
      description: Adicionar novo veiculo ao Subscritor
      operationId: "adicionarVeiculo"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Veiculo"
      responses:
        '201':
          description: O pedido foi enviado com sucesso 
        '400':
          description: Algum parametro estava incorreto
        '409': 
          description: O pedido ja se encontra criado.
    get:
      tags:
        - Subscritores
      summary: Pedir todos os veiculos
      operationId: "pedirVeiculos"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Todos os veiculos do cidadão com sessao aberta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Veiculo'
        '400':
          description: Algum parametro estava incorreto
        '404': 
          description: Recurso não encontrado

  /api/subscritores/{nif}/veiculos/{matricula}:
    delete:
      tags:
        - Subscritores
      summary: Dissociar o veiculo ao Subscritor
      operationId: "removerVeiculo"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - in: path
        name: matricula
        required: true
        description: matricula
        schema:
          type: string
      responses:
        '200':
          description: O veiculo foi removido com sucesso
        '202':
          description: Operação aceite
        '204':
          description: O veiculo especifico não se encontra na aplicaçao
        '403':
          description: não possui a autorizaçao necessaria

  /api/subscritores/{nif}/notificacoes:
    get:
      tags:
        - Subscritores
      summary: Requerer todas as notificações
      operationId: "pedirNotificações"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Todas as notificações do Subscritor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacoes'
        '400':
          description: Algum parametro estava incorreto
        '404': 
          description: Recurso não encontrado
    post:
      tags:
        - Administradores
      summary: Adicionar notificacao ao subscritor
      description: Adicionar nova notificacao ao Subscritor
      operationId: "adicionarNotificacao"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contraordenacao"
      responses:
        '201':
          description: O pedido foi enviado com sucesso 
        '400':
          description: Algum parametro estava incorreto
        '409': 
          description: O pedido ja se encontra criado.

  /api/subscritores/{nif}/notificacoes/{id}:
    get:
      tags:
        - Subscritores
      summary: Requerer a notificaçao com o id
      operationId: "pedirNotificaçao"
      parameters:
      - name: nif
        in: path
        description: nif do cidadão
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id da notificaçao
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Todas as notificações do Subscritor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contraordenacao'
        '400':
          description: Algum parametro estava incorreto
        '404': 
          description: Recurso não encontrado

  /api/login:
    post:
      tags:
      - Subscritores
      summary: Permite o Cidadão fazer login na aplicaçao
      operationId: loginDeSubscritor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        "200":
          description: Operação com sucesso
        "400":
          description: Password ou username invalido
          
  /api/logout:
    post:
      tags:
      - Subscritores
      summary: Permite o Cidadão encerrar a sessao
      operationId: logoutDeSubscritor
      responses:
        "200":
          description: Operação com sucesso
components:
  schemas:
    Subscritor:
      type: object
      properties:
        nif:
          type: string
        password:
          type: string
        notificações:
          type: object 
          items:
            $ref: '#/components/schemas/Notificacoes'
        veiculos:
          type: array
          items:
            $ref: '#/components/schemas/Veiculo'
        veiculosAlugados:
          type: array
          items:
            $ref: '#/components/schemas/Veiculo'
        delegacoes:
          type: array
          items:
            $ref: '#/components/schemas/Delegacao'
    Admin:
      type: object
      properties:
        username: 
          type: string
        password:
          type: string
    Contraordenacao:
      type: object
      properties:
        numeroAuto:
          type: string
        veiculoAutuado:
          type: string
        data:
          type: string
        local:
          type: string
        normaInfrigida:
          type: string
        distrito:
          type: string
        descricaoSumaria:
          type: string
        dataLimiteDefesa:
          type: string
        estadoDoPagamento:
          type: string
        valorDaCoima:
          type: integer
        gravidade:
          type: string
        entidadeAutuante:
          type: string
        dataNoticacao:
          type: string
    Veiculo:
      type: object
      properties:
        matricula:
          type: string
        modelo: 
          type: string
        categoria: 
          type: string
    Notificacoes:
      type: object
      properties:
        Notificacoes:
          type: array
          items:
            $ref: '#/components/schemas/Contraordenacao'
    Pagamento:
      type: object
      properties:
        metodoDePagamento: 
          type: string
    PedidoDeDefesa:
      type: object
      properties:
        id:
          type: integer
        descricao:
          type: string
    Delegacao:
      type: object
      properties:
        dataInicio:
          type: integer
        dataFim:
          type: integer
        usuario:
          type: string
    Delegacoes:
      type: object
      properties:
        delegacoes:
          type: array
          items:
            $ref: '#/components/schemas/Delegacao'
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    Cidadao:
      type: object
      properties:
        nome:
          type: string
        nif:
          type: string
        numeroConducao:
          type: string
        email:
          type: string
        password:
          type: string