DROP TABLE IF EXISTS NOTIFICACAO;
DROP TABLE IF EXISTS PUSH_SUBSCRIPTION;
DROP TABLE IF EXISTS CONTRAORDENACAO;
DROP TABLE IF EXISTS DELEGACAO;
DROP TABLE IF EXISTS VEICULO;
DROP TABLE IF EXISTS DATASUBSCRICAO;
DROP TABLE IF EXISTS SUBSCRITOR;
DROP TABLE IF EXISTS CIDADAO;