DROP TABLE IF EXISTS Pedido_Defesa;
DROP TABLE IF EXISTS Evento_Transito;
DROP TABLE IF EXISTS Emprestimo;
DROP TABLE IF EXISTS Veiculo;
DROP TABLE IF EXISTS Notificacao;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS Subscritor;
DROP TABLE IF EXISTS Pessoa;